// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkHAER-7BSJRRp0hEf4W2zU7Mg_cVJbto',
    appId: '1:769002061979:web:9efb3a44a1a6ad310b463e',
    messagingSenderId: '769002061979',
    projectId: 'meal-recommendation-5c3ac',
    authDomain: 'meal-recommendation-5c3ac.firebaseapp.com',
    storageBucket: 'meal-recommendation-5c3ac.firebasestorage.app',
    measurementId: 'G-B4HZ50N0GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLqL2SExboM2USEOwiU0VNiTCKoW8MwbI',
    appId: '1:769002061979:android:38b94fe11c49f6d90b463e',
    messagingSenderId: '769002061979',
    projectId: 'meal-recommendation-5c3ac',
    storageBucket: 'meal-recommendation-5c3ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDryaLS1ssXRK-kFUFcOZjRxUY0sIoYTD4',
    appId: '1:769002061979:ios:8797c77ca88d94900b463e',
    messagingSenderId: '769002061979',
    projectId: 'meal-recommendation-5c3ac',
    storageBucket: 'meal-recommendation-5c3ac.firebasestorage.app',
    iosBundleId: 'com.example.mealRecommendationAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDryaLS1ssXRK-kFUFcOZjRxUY0sIoYTD4',
    appId: '1:769002061979:ios:8797c77ca88d94900b463e',
    messagingSenderId: '769002061979',
    projectId: 'meal-recommendation-5c3ac',
    storageBucket: 'meal-recommendation-5c3ac.firebasestorage.app',
    iosBundleId: 'com.example.mealRecommendationAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkHAER-7BSJRRp0hEf4W2zU7Mg_cVJbto',
    appId: '1:769002061979:web:f888c38099948eb50b463e',
    messagingSenderId: '769002061979',
    projectId: 'meal-recommendation-5c3ac',
    authDomain: 'meal-recommendation-5c3ac.firebaseapp.com',
    storageBucket: 'meal-recommendation-5c3ac.firebasestorage.app',
    measurementId: 'G-LBL0Z0Z4JR',
  );
}
